# Usa una imagen base compatible con Java 26
FROM eclipse-temurin:26-jdk-alpine

# Directorio de trabajo interno
WORKDIR /app

# Copia el JAR específico de tu proyecto
COPY target/employeemanager-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto por defecto de Spring Boot
EXPOSE 8080

# Ejecuta la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]